### ISSUE TITLE
World clock

### ISSUE THREAD

**Issue by s50u** [coulisse/spiderweb#8]
Hi

It would be very useful to see real utc time clock with current date. Maybe it would fit just before "callsign" search field.

73 Danilo S50U

**Comment by coulisse** [comment]
Hello I made this change on 2.2 beta.

See it on [test.iu1bow.it](https://test.iu1bow.it)

Could you check it?

Thanks,
Corrado

**Comment by s50u** [comment]
Hi

I would prefer live clock in COOKIE format like "Current time:  **Sunday, 19-Dec-2021 12:05:49 UTC**"
See: https://www.utctime.net/

Ciao Danilo

**Comment by coulisse** [comment]
Ciao Danilo,
I preferr only hh:mm, because is more lean and less distracting, but is just a personal opinion.

However if you want, you could change  the javascript  static/js/clock.js and working on the string "time" in order to obtain your preferred formad.

Keep in mind that you have to minify the javascript executing the script in scripts/build.sh

Ciao
Corrado

**Comment by s50u** [comment]
ok I would prefer live clock from the pic.

73 Danilo

![time](https://user-images.githubusercontent.com/76863445/147418881-672bdb25-710c-4495-a4af-df642073087e.jpg)

**Comment by coulisse** [comment]
Closed with 2.2 version
